language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-arm-none-eabi gcc-aarch64-linux-gnu

script:
- bash build.sh

os: linux
dist: bionic
# nothing, just to trigger a new github actions build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build_dir/*
  overwrite: true
  draft: false
